### ISSUE TITLE
`tox-uv` in the `tox` workflow?

### ISSUE THREAD

**Issue by mxr** [asottile/workflows#69]
Would you consider a PR to add a flag to use `tox-uv` instead of `tox`? For example something like

```
inputs:
...
      uv:
        type: boolean

...
jobs:
  tox:
...
    - run: python -muv tool install tox --with tox-uv # copied from https://github.com/tox-dev/tox-uv/blob/8ed18f93b53189c51cf13719bd7b33435d7d3aae/README.md#how-to-use
      if: inputs.uv
```
